### PR TITLE
modified dark theme main logo, made it darker

### PR DESCRIPTION
**Pull request by ena-04**

### CODE REVIEW

**Comment by mrunankpawar** [comment]
Can you please add screenshots?

**Comment by ena-04** [comment]
> Hey @ena-04, can you please add screenshots?

i had already added it in the issue that you closed, i had forgotten to push the changes
Screenshot (172)
Screenshot (171)

**Comment by mrunankpawar** [comment]
Did you make similar changes for other pages as well?

**Comment by ena-04** [comment]
> Did you make similar changes for other pages as well?

Yes i did

**Comment by mrunankpawar** [comment]
Can you please work on changing the logo in dark mode for other pages as well?(As you did it for the home page)

**Comment by ena-04** [comment]
> @ena-04 Can you please work on changing the logo in dark mode for other pages as well? (As you did it for the home page)

yep done

**Pull request merged**
